# Site settings
title: Engineering Statics Welcome Page
email: dan.baker@colostate.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/creative-theme-jekyll/" # the subpath of your site, e.g. /blog/
url: "https://dantheboatman.github.io/" # the base hostname & protocol for your site

twitter_username: drdanteaches
github_username: 

# Build settings
markdown: kramdown
