# Site settings
title: Engineering Statics Welcome Page
email: dan.baker@colostate.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://engineeringstatics.org/" # the base hostname & protocol for your site
destination : ../../site  # puts rendered landing page into pretext site folder.
twitter_username: drdanteaches
github_username: 

# Build settings
markdown: kramdown
