namespace html = "http://www.w3.org/1999/xhtml"
namespace xml = "http://www.w3.org/XML/1998/namespace"
namespace svg = "http://www.w3.org/2000/svg"

include "../../../mathbook/schema/pretext-dev.rnc"



# permits Images in table cells,  This is not supported by the xslt or in Latex. 4/23/22
TableCell |=
    element cell {
        AlignmentHorizontal?,
        BorderBottom?,
        BorderRight?,
        attribute colspan { text }?,
        (TextLong
            | LongLine+
            | element p { UniqueID?, Image }+)
    }

# create attribution element for License Info
Remix_info =
    element remix {
        (element title { text }
            | element creator {
                        attribute href { text }?,
                        text?
                    }
            | element source {
                        attribute href { text }?,
                        text?
                    }
            | element license {
                        attribute href { text }?,
                        text?
                    }
            | element note { text })*
    }

# allows remix_info in images and interactives

ImageRaster |=
                element image {
                    UniqueID?,
                    Component?,
                    attribute width {text}?,
                    attribute margins {text}?,
                    attribute rotate {text}?,
                    attribute archive {text}?,
                    attribute source {text},
                    (
                      attribute decorative {"yes"} |
                      (
                        attribute decorative {"no"}?,
                        (
                          ImageShortDescription? &
                          ImageDescription? &
                          Remix_info?  #weh
                        )
                      )
                    )
                }
Interactive |=
                element interactive {
                    UniqueID?,
                    LabelID?,
                    Component?,
                    attribute aspect { text }?,
                    attribute width { text }?,
                    attribute platform { text }?,
                    attribute preview { text }?,
                    attribute iframe { text }?,
                    attribute source { text }?,
                    attribute version { text }?,
                    attribute circuitjs { text }?,
                    attribute calcplot3d { text }?,
                    attribute geogebra { text }?,
                    attribute desmos { text }?,
                    # currently only consumed by the CalcPlot3D flavor;
                    # widen this enum if another flavor adopts "@variant"
                    attribute variant { "application" | "controls" | "minimal" }?,
                    attribute dark-mode-enabled { text }?,
                    attribute resize-behavior { text }?,
                    attribute css { text }?,
                    attribute design-width { text }?,
                    attribute reset-icon { text }?,
                    (
                      ImageShortDescription? &
                      ImageDescription? &
                      (
                        Slate |
                        SideBySideNoNumber |
                        SideBySideGroupNoNumber
                      )* &
                      element script { attribute type { text }?, text }* &
                      element source { text }? &
                      element instructions { mixed { MetaDataTitleOptional, BlockText+ } }? &
                      Remix_info? &
                      element static { Image }?
                    )

                }
                
#permits raw svg content in slates, required so that javascript can manipulate individual parts of the diagram.
#only works when svg is added using xi:include, including it as image@source doesn't work
#Used in chapter 8 graphical methods interactives
                
SVGContent = (text | element svg:* { attribute * { text }*, SVGContent* })*

Slate |=
    element slate {
        UniqueID?,
        LabelID?,
        Component?,
        attribute surface { "svg" },
        attribute aspect { text }?,
        element svg:svg {
            attribute * { text }*,
            SVGContent
        }
    }