namespace html = "http://www.w3.org/1999/xhtml"
namespace xml = "http://www.w3.org/XML/1998/namespace"
namespace svg = "http://www.w3.org/2000/svg"

include "../../../mathbook/schema/pretext-dev.rnc"



# permits Images in table cells,  This is not supported by the xslt or in Latex. 4/23/22
TableCell |=
    element cell {
        AlignmentHorizontal?,
        BorderBottom?,
        BorderRight?,
        attribute colspan { text }?,
        (TextLong
            | LongLine+
            | element p { UniqueID?, Image }+)
    }

# Custom <remix> attribution element for License Info.
# remix elements are included with images and interactives.
# remix elements are not ever rendered, so are commented out to not pollute validation reports. 9/12/26
# perhaps someday standard pretext will provide a mechanism to capture image attribution metadata


Remix_info =
    element remix {
        (element title { text }
            | element creator {
                        attribute href { text }?,
                        text?
                    }
            | element source {
                        attribute href { text }?,
                        text?
                    }
            | element license {
                        attribute href { text }?,
                        text?
                    }
            | element note { text })*
    }



#permits raw svg content in slates, required so that javascript can manipulate individual parts of the diagram.
#only works when svg is added using xi:include, including it as image@source doesn't work
#Used in chapter 8 graphical methods interactives
                
SVGContent = (text | element svg:* { attribute * { text }*, SVGContent* })*

Slate |=
    element slate {
        UniqueID?,
        LabelID?,
        Component?,
        attribute surface { "svg" },
        attribute aspect { text }?,
        element svg:svg {
            attribute * { text }*,
            SVGContent
        }
    }